[tool.ruff]
target-version = "py311"
line-length = 88
src = ["scripts", "src", "notebook"]
extend-exclude = [
    "scGPT",
    "data/",
    "docs/",
]

[tool.ruff.lint]
select = ["E", "W", "F"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

